{"uuid": "22dd258d-0a3c-4020-ae87-7a29dfba6e24", "children": ["5541c86d-8ba4-4544-a875-570465e197e6"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: New session attempts retry count exceeded\n\n", "trace": "  File \"/home/gwynbleidd/.local/lib/python3.8/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/gwynbleidd/.local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/gwynbleidd/.local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/home/gwynbleidd/Рабочий стол/2021-2-QA-AUTO-PYTHON-VKGROUP-S-ASTAKHOV/final_proj/test_folder/ui/fixtures.py\", line 21, in driver\n    browser = webdriver.Remote(command_executor=f'http://{SELENOID_HOST}:{SELENOID_PORT}/wd/hub',\n  File \"/home/gwynbleidd/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 266, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/home/gwynbleidd/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 357, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"/home/gwynbleidd/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 418, in execute\n    self.error_handler.check_response(response)\n  File \"/home/gwynbleidd/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1639861266958, "stop": 1639861337328}], "start": 1639861266958, "stop": 1639861337669}